disabled_rules:
  - line_length
  - trailing_whitespace
  - type_body_length
  - file_length
  - colon
  - comma
  - force_cast
  - force_try
  - large_tuple
  - function_body_length

opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - empty_count
  - explicit_init
  - fatal_error_message
  - first_where
  - last_where
  - implicit_return
  - multiline_parameters
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - vertical_parameter_alignment_on_call
  - trailing_closure
  - discouraged_direct_init
  - unneeded_parentheses_in_closure_argument
  - array_init
  - multiline_arguments
  - literal_expression_end_indentation
  - sorted_first_last
  - override_in_extension
  - discouraged_object_literal
  - strict_fileprivate
  - convenience_type
  - no_extension_access_modifier
  - modifier_order
  - anyobject_protocol
  - unused_private_declaration
  - unused_import
  - identical_operands
  - collection_alignment
  - static_operator
  - multiline_literal_brackets
  - vertical_whitespace_opening_braces
  - vertical_whitespace_closing_braces
  - xct_specific_matcher
  - strong_iboutlet
  - legacy_random
  - toggle_bool
  - duplicate_imports
  - unused_setter_value


# Rule configuration

cyclomatic_complexity:
  ignores_case_statements: true

nesting:
  type_level:
    warning: 3

identifier_name:
  max_length: 60
  excluded:
    - id
    - i
    - j
    - n

type_name:
  max_length: 60
